package com.example.skripsi.cobain;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public class DataHelper extends SQLiteOpenHelper {
    private static final String DATABASE_NAME = "madura.db";
    private static final int DATABASE_VERSION = 1;
    public DataHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
        // TODO Auto-generated constructor stub
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        // TODO Auto-generated method stub
        String sql = "create table datakamus(id integer PRIMARY KEY AUTOINCREMENT, indonesia text, madura text);";
        Log.d("Data", "onCreate: " + sql);
        db.execSQL(sql);
        sql = "INSERT INTO datakamus (indonesia, madura) VALUES " + "('alis', 'alis'),"+
                "('abah','abah'),"+
                "('abadi','abadi'),"+
                "('abal-abal','akalpokal'),"+
                "('abang','abang'),"+
                "('abu-abu','buabuh'),"+
                "('acara','acara'),"+
                "('ada','bedeh'),"+
                "('adat','adet'),"+
                "('adem','adem'),"+
                "('administrasi','administrasi'),"+
                "('adu domba','adu domba'),"+
                "('agama','agemah'),"+
                "('agamais','agamais'),"+
                "('ajak','ajek'),"+
                "('akhir','akher'),"+
                "('akhlak','akhlak'),"+
                "('akibat','polanah'),"+
                "('akrab','akrab'),"+
                "('aksen','aksen'),"+
                "('akses','akses'),"+
                "('aktif','aktif'),"+
                "('akur','akor'),"+
                "('alam','alam'),"+
                "('alamat','alamat'),"+
                "('alat','alat'),"+
                "('amatir','amatir'),"+
                "('ambil','kalak'),"+
                "('ambruk','robbu'),"+
                "('ambulan','ambulan'),"+
                "('anak','anak'),"+
                "('ananda','putra'),"+
                "('anda','sampean'),"+
                "('aneh','aneh'),"+
                "('anjing','patek'),"+
                "('antar','ater'),"+
                "('antri','ngantri'),"+
                "('arti','arteh'),"+
                "('asam','asem'),"+
                "('aset','aset'),"+
                "('asli','asli'),"+
                "('atap','gebek'),"+
                "('ayam','ajem'),"+
                "('babe','babe'),"+
                "('babi','bebbih'),"+
                "('bacot','bacot'),"+
                "('badak','badak'),"+
                "('badai','badai'),"+
                "('badan','beden'),"+
                "('badminton','badminton'),"+
                "('bagaimana','beremma'),"+
                "('bagasi','bagasi'),"+
                "('bagi','bagi'),"+
                "('bagus','begus'),"+
                "('bahagia','bahagia'),"+
                "('bahan','bahan'),"+
                "('bahasa','besah'),"+
                "('bahaya','bebejeh'),"+
                "('bahkan','bahkan'),"+
                "('bahu','behu'),"+
                "('bakar','obber'),"+
                "('balap','balap'),"+
                "('bambu','bambu'),"+
                "('bambang','bambang'),"+
                "('banci','banci'),"+
                "('bandung','bandung'),"+
                "('bangga','bangga'),"+
                "('bangkit','bangkit'),"+
                "('bangku','bangku'),"+
                "('bangsat','bangsat'),"+
                "('bangsawan','bangsawan'),"+
                "('banjir','banjir'),"+
                "('bank','bank'),"+
                "('bantah','bantah'),"+
                "('bantai','bantai'),"+
                "('bantal','bantal'),"+
                "('banteng','banteng'),"+
                "('banting','benteng'),"+
                "('bantu','bentoh'),"+
                "('banyak','benyak'),"+
                "('bapak','eppak'),"+
                "('barang','bereng'),"+
                "('barangkali','barangkali'),"+
                "('barat','berek'),"+
                "('barbar','barbar'),"+
                "('bareng','bereng'),"+
                "('baris','beris'),"+
                "('barongsai','barongsai'),"+
                "('basi','basi'),"+
                "('basket','basket'),"+
                "('batang','batang/rancak'),"+
                "('batas','bettes'),"+
                "('batik','batik'),"+
                "('batu','bettoh'),"+
                "('bau','bettoh'),"+
                "('baud','beut'),"+
                "('bawah','bebe'),"+
                "('beban','beban'),"+
                "('badan','beden'),"+
                "('bebas','bebasn'),"+
                "('becak','becak'),"+
                "('becek','becek'),"+
                "('beda','laen'),"+
                "('bedak','beddek'),"+
                "('begal','begal'),"+
                "('belakang','buddih'),"+
                "('belimbing','belimbing'),"+
                "('belut','belut'),"+
                "('bengkel','bengkel'),"+
                "('bengkok','pettok'),"+
                "('benjol','bennol'),"+
                "('bensin','bensin'),"+
                "('bentar','sagejjek'),"+
                "('bentuk','bentuk'),"+
                "('berak','ataeh'),"+
                "('berangkat','mangkat'),"+
                "('berani','bengal'),"+
                "('berapa','berempah'),"+
                "('beras','berres'),"+
                "('berat','berrek'),"+
                "('berengsek','berengsek'),"+
                "('berewok','berewok'),"+
                "('beringas','beringas'),"+
                "('berisik','enger'),"+
                "('berita','berita'),"+
                "('berkas','berkas'),"+
                "('berkat','berkat'),"+
                "('berlian','berlian'),"+
                "('berontak','berontak'),"+
                "('bersih','berseh'),"+
                "('bersin','ajjiman'),"+
                "('besar','rajjeh'),"+
                "('besok','laggunah'),"+
                "('betina','betina'),"+
                "('betis','bettes'),"+
                "('beton','beton'),"+
                "('betul','bennder'),"+
                "('biadab','biadab'),"+
                "('biasa','biassah'),"+
                "('biawak','biawak'),"+
                "('biaya','biaya'),"+
                "('bibir','bibir'),"+
                "('bibit','bibit'),"+
                "('bicara','acaca'),"+
                "('bidadari','bidadari'),"+
                "('bidan','bidan'),"+
                "('biduan','biduan'),"+
                "('bijaksana','bijaksana'),"+
                "('biksu','biksu'),"+
                "('bilal','bilal'),"+
                "('bilang','kocak'),"+
                "('bilas','bilas'),"+
                "('bimbang','bimbang'),"+
                "('binatang','keben'),"+
                "('bingkai','bingkai'),"+
                "('bingung','bihngung'),"+
                "('bintang','bintang'),"+
                "('biodata','biodata'),"+
                "('biografi','biografi'),"+
                "('biola','biola'),"+
                "('biologi','biologi'),"+
                "('bioskop','bioskop'),"+
                "('biru','biruh'),"+
                "('bisa','bissah'),"+
                "('bisbol','bisbol'),"+
                "('bising','enger'),"+
                "('bismillah','bismillah'),"+
                "('bisu','bisu'),"+
                "('blog','blog'),"+
                "('bloger','bloger'),"+
                "('bobol','bobol'),"+
                "('bobot','bobot'),"+
                "('bobrok','bobrok'),"+
                "('bocah','rek-kerek'),"+
                "('bocor','bucor'),"+
                "('bodoh','budduh'),"+
                "('bogor','bogor'),"+
                "('bohong','lecek'),"+
                "('boikot','boikot'),"+
                "('bola','ball'),"+
                "('boleh','olle'),"+
                "('bolos','bolos'),"+
                "('bolot','bolot'),"+
                "('bom','bom'),"+
                "('bolu','bolu'),"+
                "('bonceng','ngentel'),"+
                "('boneka','boneka'),"+
                "('bongkar','bungkar'),"+
                "('bongkol','bongkol'),"+
                "('bongok','bongok'),"+
                "('bonjol','bonjol'),"+
                "('bontot','bontot'),"+
                "('bonus','bonus'),"+
                "('bonyok','bonyok'),"+
                "('bopong','bopong'),"+
                "('borgol','borgol'),"+
                "('borong','deppes'),"+
                "('boros','boros'),"+
                "('botak','butak'),"+
                "('botol','butol'),"+
                "('brahma','brahma'),"+
                "('brengsek','brengsek'),"+
                "('buah','bue'),"+
                "('buat','gebey'),"+
                "('buaya','bejjeh'),"+
                "('bubar','bubar'),"+
                "('bubur','tajin'),"+
                "('buddha','buddeh'),"+
                "('budek','budek'),"+
                "('bukan','benni'),"+
                "('bukti','bukteh'),"+
                "('beban','beban'),"+
                "('bulu','bulluh'),"+
                "('bumbu','bumbu'),"+
                "('bumi','bummih'),"+
                "('bunda','bunda'),"+
                "('bunga','gembeng'),"+
                "('buntu','buntu'),"+
                "('bunuh','ngekill'),"+
                "('bunyi','bunnyih'),"+
                "('burung','manuk'),"+
                "('butuh','buto'),"+
                "('cabe','cabbih'),"+
                "('campur','campor'),"+
                "('cangkir','cangker'),"+
                "('cantik','raddhin'),"+
                "('capek','lessoh'),"+
                "('cari','nyareh'),"+
                "('cegah','langlang'),"+
                "('celurit','sadek'),"+
                "('cendol','jindul'),"+
                "('cibir','nyenyeh'),"+
                "('cilik','cilik'),"+
                "('cincin','sellok'),"+
                "('cium','siom'),"+
                "('coba','cobak'),"+
                "('congek','kopok'),"+
                "('contoh','conto'),"+
                "('cowok','cowok'),"+
                "('cukup','cokop'),"+
                "('cukur','cokor'),"+
                "('cuman','coman'),"+
                "('curiga','curiga'),"+
                "('daging','deging'),"+
                "('dahulu','dulluh'),"+
                "('dakwah','dakwah'),"+
                "('dalam','delem'),"+
                "('danau','danau'),"+
                "('dapat','olle'),"+
                "('dasar','desar'),"+
                "('data','data'),"+
                "('datar','datar'),"+
                "('daun','deun'),"+
                "('dekan','dekan'),"+
                "('dendam','dendam'),"+
                "('derajat','derajat'),"+
                "('deres','derres'),"+
                "('desa','disah'),"+
                "('desah','desah'),"+
                "('desain','desain'),"+
                "('desember','Desember'),"+
                "('detik','detik'),"+
                "('dewasa','dewasa'),"+
                "('di','e'),"+
                "('dialek','dialek'),"+
                "('diam','diem'),"+
                "('digital','digital'),"+
                "('dikit','sakonik'),"+
                "('diskon','diskon'),"+
                "('doa','doa'),"+
                "('doang','gun'),"+
                "('dokter','dokter'),"+
                "('domba','domba'),"+
                "('dompet','dompet'),"+
                "('dua','duek'),"+
                "('duafa','duafa'),"+
                "('duduk','tojuk'),"+
                "('dukun','dukon'),"+
                "('dunia','dunyah'),"+
                "('duri','durih'),"+
                "('durian','durian'),"+
                "('dusta','dusta'),"+
                "('dusun','dusun'),"+
                "('dulu','dulluh'),"+
                "('dandan','dandan'),"+
                "('dagu','janggut'),"+
                "('darah','dere'),"+
                "('dengar','ngeding'),"+
                "('dari','deri'),"+
                "('depan','adek'),"+
                "('datang','deeteng'),"+
                "('dingin','geddung'),"+
                "('edisi','edisi'),"+
                "('edit','edit'),"+
                "('efek','efek'),"+
                "('ego','ego'),"+
                "('ekonomi','ekonomi'),"+
                "('ekor','buntok'),"+
                "('elang','elang'),"+
                "('elemen','elemen'),"+
                "('email','email'),"+
                "('emas','emas'),"+
                "('ember','ember'),"+
                "('empat','empat'),"+
                "('enak','nyaman'),"+
                "('enam','enem'),"+
                "('encok','encok'),"+
                "('engkau','engkau'),"+
                "('es','es'),"+
                "('etika','bebetek'),"+
                "('fikiran','pekeran'),"+
                "('faedah','faedah'),"+
                "('fase','fase'),"+
                "('februari','februari'),"+
                "('film','film'),"+
                "('final','final'),"+
                "('finis','finis'),"+
                "('fisik','fisik'),"+
                "('fisika','fisika'),"+
                "('fitnah','fitnah'),"+
                "('fokus','fokus'),"+
                "('foto','foto'),"+
                "('fungsi','fungsi'),"+
                "('gabung','gabung'),"+
                "('gadis','prabhen'),"+
                "('gajah','geje'),"+
                "('gambar','gember'),"+
                "('gampang','gempang'),"+
                "('gampar','tapok'),"+
                "('ganteng','genteng'),"+
                "('gatal','getel'),"+
                "('gaya','geye'),"+
                "('geli','geliek'),"+
                "('gelap','petteng'),"+
                "('gembira','perak'),"+
                "('gempa','gempa'),"+
                "('gudang','gudeng'),"+
                "('gula','gulleh'),"+
                "('gendut','lempo'),"+
                "('ganti','genteh'),"+
                "('garam','buje'),"+
                "('gigi','giggih'),"+
                "('habis','tadek'),"+
                "('hamil','ngandung'),"+
                "('hancur','ancor'),"+
                "('hantu','dindedin'),"+
                "('harga','argeh'),"+
                "('hari','areh'),"+
                "('harum','rok-om'),"+
                "('hasil','hasel'),"+
                "('haus','pelkak'),"+
                "('hewan','keben'),"+
                "('hijau','biruh'),"+
                "('hidung','elong'),"+
                "('hilang','elang'),"+
                "('harimau','macan'),"+
                "('hujan','ojen'),"+
                "('hutang','otang'),"+
                "('hidup','odik'),"+
                "('hutan','alas'),"+
                "('hati','atteh'),"+
                "('ingat','engak'),"+
                "('ibu','ebuh'),"+
                "('ikan','jukok'),"+
                "('ilmu','elmoh'),"+
                "('ini','riah'),"+
                "('ikat','iket'),"+
                "('iya','enggi'),"+
                "('itu','genikah'),"+
                "('ikut','norok'),"+
                "('jagung','jegung'),"+
                "('jahat','jahat'),"+
                "('jajan','jejen'),"+
                "('jam','jem'),"+
                "('jantung','jantung'),"+
                "('januari','januari'),"+
                "('jatuh','labu'),"+
                "('jawab','jeweb'),"+
                "('jemput','koniin'),"+
                "('jendala','jendela'),"+
                "('jerapah','jerapah'),"+
                "('jerawat','jerebek'),"+
                "('jijik','bejik'),"+
                "('jodoh','judduh'),"+
                "('juli','juli'),"+
                "('jumlah','jumleh'),"+
                "('juni','juni'),"+
                "('jauh','jeu'),"+
                "('jidat','deih'),"+
                "('jalan','jelen'),"+
                "('jadi','jeddi'),"+
                "('jari','gerigik'),"+
                "('jamu','jemmuh'),"+
                "('jenggot','jengguk'),"+
                "('jeruk','jerruk'),"+
                "('jual','juel'),"+
                "('jangan','empon'),"+
                "('jarang','rang rang'),"+
                "('kabar','kaber'),"+
                "('kaget','takerjet'),"+
                "('kakak','abhang'),"+
                "('kaki','sokkoh'),"+
                "('kambing','mbik'),"+
                "('kamis','kemmis'),"+
                "('kapan','billeh'),"+
                "('kaya','soghi'),"+
                "('ke','ka'),"+
                "('keliru','kaleroh'),"+
                "('keluarga','kaloarga'),"+
                "('kenapa','arapah'),"+
                "('kontol','peller'),"+
                "('kota','kottah'),"+
                "('kembali','abelih'),"+
                "('kumis','jengguk'),"+
                "('kakek','mbah'),"+
                "('kepala','socah'),"+
                "('kentut','akentok'),"+
                "('kuda','jeren'),"+
                "('kacamata','kacamatah'),"+
                "('kalung','kalong'),"+
                "('kayu','kajjuh'),"+
                "('kerbau','kerbau'),"+
                "('keris','keres'),"+
                "('kamu','sampean'),"+
                "('keringat','kringet'),"+
                "('kubur','kobur'),"+
                "('kurang','korang'),"+
                "('kuat','kuat'),"+
                "('kuku','kuku'),"+
                "('keluar','kalowar'),"+
                "('kabur','kabur'),"+
                "('kerja','lakoh'),"+
                "('kata','pakon'),"+
                "('lain','laen'),"+
                "('lelaki','lalakek'),"+
                "('lepas','locot'),"+
                "('lihat','abes'),"+
                "('lutut','tok ot'),"+
                "('leher','le er'),"+
                "('lidah','ilat'),"+
                "('lauk','jukok'),"+
                "('lagi','pole'),"+
                "('lahir','laher'),"+
                "('lewat','lebet'),"+
                "('luas','loas'),"+
                "('lama','abit'),"+
                "('maaf','saporannah'),"+
                "('maksud','maksod'),"+
                "('mama','ebok'),"+
                "('mati','matteh'),"+
                "('mobil','motor'),"+
                "('mandi','mandih'),"+
                "('merah','mera'),"+
                "('mau','endek'),"+
                "('mulut','colok'),"+
                "('mana','dimmah'),"+
                "('malu','todus'),"+
                "('minta','mitah'),"+
                "('makam','kuburen'),"+
                "('mahal','larang'),"+
                "('mata','matah'),"+
                "('mayat','mayit'),"+
                "('makan','ngakan'),"+
                "('meninggal','mateh'),"+
                "('murah','mude'),"+
                "('mimpi','ngimpi'),"+
                "('minum','ngenom'),"+
                "('makanan','kakanan'),"+
                "('malam','malem'),"+
                "('nama','nyamah'),"+
                "('negara','nagereh'),"+
                "('nyawa','nyabeh'),"+
                "('nikah','kabin'),"+
                "('nilai','nilai'),"+
                "('otak','otek'),"+
                "('obat','obat'),"+
                "('ompong','ompong'),"+
                "('orang','oreng'),"+
                "('pasti','pasteh'),"+
                "('pedas','pedes'),"+
                "('perawan','paraben'),"+
                "('pergi','entar'),"+
                "('permen','manisan'),"+
                "('pijit','orok'),"+
                "('pindah','ngalle'),"+
                "('pojok','patduh'),"+
                "('pantat','bokong'),"+
                "('pegang','tegguk'),"+
                "('potong','cokor'),"+
                "('punya','andik'),"+
                "('pagi','lagguh'),"+
                "('pakai','angguy'),"+
                "('punggung','buggik'),"+
                "('pria','lalakek'),"+
                "('pencuri','maleng'),"+
                "('pulang','mole'),"+
                "('pegang','tegguk'),"+
                "('pinjam','nginjem'),"+
                "('payung','pajung'),"+
                "('panas','panas'),"+
                "('perintah','perentah'),"+
                "('pikir','pikir'),"+
                "('pipi','pipi'),"+
                "('pijat','peccet'),"+
                "('peluk','rangkul'),"+
                "('perhiasan','sandhangan'),"+
                "('rajin','kodduh'),"+
                "('rambut','obuk'),"+
                "('remaja','bhindereh'),"+
                "('rokok','rokok'),"+
                "('rugi','rogi'),"+
                "('rata','rattah'),"+
                "('sabar','sabber'),"+
                "('sabtu','sabtoh'),"+
                "('sabun','sabon'),"+
                "('sakti','sakteh'),"+
                "('salah','salah'),"+
                "('samping','sampeng'),"+
                "('sarung','sarong'),"+
                "('sate','sate'),"+
                "('satu','sittong'),"+
                "('saya','kauleh'),"+
                "('sedikit','sakonik'),"+
                "('sekarang','satiah'),"+
                "('selatan','laok'),"+
                "('selesai','mareh'),"+
                "('senang','perak'),"+
                "('sepeda','sepeda pancal'),"+
                "('siang','aben'),"+
                "('siapa','sappah'),"+
                "('sini','dinnak'),"+
                "('suka','sokkah'),"+
                "('sungai','songai'),"+
                "('sendiri','dibik'),"+
                "('suap','dulang'),"+
                "('semua','kabbi'),"+
                "('selimut','salemok'),"+
                "('suruh','soro'),"+
                "('sakit','sakek'),"+
                "('sama','paddeh'),"+
                "('sapi','sappeh'),"+
                "('sabuk','sabuk'),"+
                "('sebentar','sagejek'),"+
                "('sendok','sendok'),"+
                "('selamat','slamet'),"+
                "('suara','swara'),"+
                "('susu','susu'),"+
                "('sehat','sae'),"+
                "('senyum','senyum'),"+
                "('tadi','gellek'),"+
                "('tahun','taon'),"+
                "('tau','oning'),"+
                "('teman','kanca'),"+
                "('terima','taremmah'),"+
                "('terus','teros'),"+
                "('tidak','enjjek'),"+
                "('tikus','tekos'),"+
                "('timur','temor'),"+
                "('tua','seppoh'),"+
                "('tulang','tolang'),"+
                "('tunggu','entos'),"+
                "('tambah','tambeh'),"+
                "('teriak','acereng'),"+
                "('tari','tari'),"+
                "('terkejut','takerjet'),"+
                "('telinga','kopeng'),"+
                "('tanah','tana'),"+
                "('turun','toron'),"+
                "('tangis','nangis'),"+
                "('tidur','tedung'),"+
                "('takut','takok'),"+
                "('uang','pesse'),"+
                "('umur','omor'),"+
                "('utuh','otoh'),"+
                "('ungu','biruh'),"+
                "('vagina','pokeh'),"+
                "('wadah','bedde'),"+
                "('wajib','wejib'),"+
                "('waktu','bekto'),"+
                "('wajah','moah'),"+
                "('wujud','ropa'),"+
                "('wanita','bebinik'),"+
                "('yakin','yaken'),"+
                "('zakat','zakat');";
        db.execSQL(sql);

    }

    @Override
    public void onUpgrade(SQLiteDatabase arg0, int arg1, int arg2) {
        // TODO Auto-generated method stub

    }

}
